#! /usr/bin/env bash

update_repo(){
  echo -e "\nUpdate local repository\n"
  git pull
}

update_flake(){ 
  echo -e "\nUpdate repo flake\n"
  nix flake update --flake .
}

check_rev_change(){
  if [[ -n $(git status --porcelain) ]]; then

    ### Get version and hash commit
    NIXPKGS_COMMIT=$(jq -r '.nodes."nixpkgs".locked.rev' flake.lock|cut -c1-8)
    echo -e "New revision\n"
    git add flake.lock
    git commit -m "[nixpkgs/${NIXPKGS_COMMIT}] flake.lock: update to the new rev"

    ### Push changes
    git push origin flake

    echo -e "\nChange commited to the repo"
  else
    echo "No changes detected"
  fi
}

main(){
  update_repo
  update_flake
  check_rev_change
}

### Execute the main function
main
